.\"
.\" Copyright (C) 2001 Sergey N. Belinsky.
.\"
.TH "DB2TKSH" "1" "19 December 2001" "Application" ""
.SH NAME
db2tksh \- IBM DB2 TCL shell client
.SH SYNOPSIS
db2tksh [ \fIfilename\fR ]
.SH "DESCRIPTION"
\fBpgtksh\fR provides  a  graphical  TCL/TK shell interface for IBM DB2.
.PP
\fIfilename\fR \- filename of TK/TCL script witch will be executed.
.SH AUTHOR
Written by Sergey N. Belinsky.
.SH "REPORTING BUGS"
Report bugs to <belinsky@appliedtech.org>.
.SH COPYRIGHT
Copyright \(co 2001 Sergey N. Belinsky.
.SH "SEE ALSO"
db2tclsh(1), wish(1), tclsh(1)
