.\"
.\" Copyright (C) 2001 Sergey N. Belinsky.
.\"
.TH "DB2TCLSH" "1" "19 December 2001" "Application" ""
.SH NAME
db2tclsh \- IBM DB2 TCL shell client
.SH SYNOPSIS
db2tclsh [ \fIfilename\fR ]
.SH "DESCRIPTION"
\fBdb2tclsh\fR provides a TCL shell interface for IBM DB2.
.PP
\fIfilename\fR \- filename of TCL script witch will be executed.
.SH AUTHOR
Written by Sergey N. Belinsky.
.SH "REPORTING BUGS"
Report bugs to <belinsky@appliedtech.org>.
.SH COPYRIGHT
Copyright \(co 2001 Sergey N. Belinsky.
.SH "SEE ALSO"
db2tksh(1), wish(1), tclsh(1)