#!/bin/sh
########################################################################
# \
export LD_LIBRARY_PATH=.././lib:.././lib64:$LD_LIBRARY_PATH
# \
export PATH=.././bin:$PATH
# \
exec .././bin/tclsh9.0 $0 ${1+"$@"}
# \
exit
########################################################################
# HammerDB Metrics
#
# Adapted from http://wiki.tcl.tk/37820
# mpstatPlot -- visual display of mpstat idle value for all processors
# by Keith Vetter
#
# Copyright (C) Steve Shaw
# Hosted by the TPC-Council
# Author contact information at: http://www.hammerdb.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public
# License along with this program; If not, see <https://www.gnu.org/licenses/>
########################################################################
#load files
#Accept argument of port for agent to run on. No argument generates random port number
 if {$argc == 0} {
	set port {}
	set restart true
 	} else {
    if {$argc != 1} {
	puts {Usage: agent port}
	#exit
	} else {
	set restart false
        set port [lindex $argv 0]
	if { ![string is entier $port] } {
	puts {Usage: agent port}
	#exit
	     } else { ; }
          } 
	}
set UserDefaultDir [ file dirname [ info script ] ]
::tcl::tm::path add ::tcl::tm::path add [zipfs root]app/modules "../$UserDefaultDir/modules"
lappend auto_path "[zipfs root]app/lib"
package require comm
namespace import comm::*
#Enable report for more than 122 CPUs
interp recursionlimit {} 3000
global agentlist S iswin
set iswin "false"
set version 5.0

if {$tcl_platform(platform) == "windows"} { 
	package require twapi 
	set iswin "true"
	} else {
#Remove AMPM from mpstat output
set env(LANG) "POSIX"
	} 

proc SendOneLine {line} {
#Sending one line to remote display connection
global agentlist
Agent send [ lindex $agentlist 0 ] [lindex $agentlist 1 ] StatsOneLine [list $line ]
}

proc SendIOLine { iops mbps } {
global agentlist
set iops [format "%.2f" $iops]
set mbps [format "%.2f" $mbps]
foreach f $agentlist {
    if {[catch {Agent send $f StatsOneLine [list [list IOSTAT $iops $mbps]]}]} {
        # Ignore transient send errors; normal agent reconnection logic handles disconnects.
    }
}
}

proc lremove { list item {all ""} } {
  set index [lsearch -exact $list $item]
  if {$index == -1} { return $list }
  if {$all == ""} {
    return [lreplace $list $index $index]
  } else {
    while {$index != -1} {
      set list [lreplace $list $index $index]
      set index [lsearch -exact $list $item]
    }
    return $list
}} 

proc HowManyProcessorsWindows {} {
global S cpu_model
set cpu_model [lindex [twapi::get_processor_info 0 -processorname] 1]
set ::S(cpus) [twapi::get_processor_count]
set proc_groups [ twapi::get_processor_group_config ]
set max_groups [ dict get $proc_groups -maxgroupcount ] 
set active_groups [ dict size [ dict get $proc_groups -activegroups ] ]
if { $active_groups > 1 } {
puts "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
puts "Windows system with multiple processors groups\nMaximum groups on this system $max_groups active groups $active_groups"
for {set i 0} {$i < $active_groups} {incr i} {
dict set proc_group_map $i [ dict get [ dict get $proc_groups -activegroups ] $i -activeprocessorcount ] 
puts -nonewline "Group $i has "
puts -nonewline [ dict get $proc_group_map $i ]
puts " active processors"
		}
set numa_nodes [ twapi::get_numa_config ]
set numa_node_count [ dict size $numa_nodes ]
set cpus_per_node [ expr $::S(cpus) / $numa_node_count ]
puts "System has $numa_node_count NUMA nodes and $cpus_per_node CPUs per node"
for {set i 0} {$i < $numa_node_count} {incr i} {
dict set numa_group_map $i [ dict get $numa_nodes $i -group ] 
puts -nonewline "NUMA node $i is in processor group "
puts [ dict get $numa_group_map $i ]
	}
puts "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
    }
}

proc DiscoverSystemWindows {} {
global S cpu_model sysinfo
set sysinfo [dict create]
dict set sysinfo cpumodel $cpu_model
dict set sysinfo cpucount $S(cpus)
#OS Name and Version
if { [catch {
    set osver [twapi::get_os_version]
    set osdesc [twapi::get_os_description]
    dict set sysinfo os_name "$osdesc (Build [join $osver .])"
} err] } {
    dict set sysinfo os_name "Windows (version unavailable)"
}
#System Vendor and Type via WMI
if { [catch {
    set wmi [twapi::_wmi]
    set items [$wmi ExecQuery "SELECT Manufacturer,Model FROM Win32_ComputerSystem"]
    $items -iterate item {
        dict set sysinfo system_vendor [$item -get Manufacturer]
        dict set sysinfo system_type [$item -get Model]
        $item destroy
    }
    $items destroy
    $wmi destroy
} err] } {
    dict set sysinfo system_vendor "Unknown"
    dict set sysinfo system_type "Unknown"
}
#Total Physical Memory via WMI
if { [catch {
    set wmi [twapi::_wmi]
    set items [$wmi ExecQuery "SELECT TotalPhysicalMemory FROM Win32_ComputerSystem"]
    $items -iterate item {
        set totalmem [$item -get TotalPhysicalMemory]
        set totalmem_gb [format "%.1f" [expr {$totalmem / 1073741824.0}]]
        dict set sysinfo memory "${totalmem_gb} GB"
        $item destroy
    }
    $items destroy
    $wmi destroy
} err] } {
    dict set sysinfo memory "Unknown"
}
#NIC Information via WMI
if { [catch {
    set wmi [twapi::_wmi]
    set items [$wmi ExecQuery "SELECT Description,Speed FROM Win32_NetworkAdapter WHERE NetConnectionStatus=2"]
    set niclist [list]
    $items -iterate item {
        set nicdesc [$item -get Description]
        if { [catch {set nicspeed [$item -get Speed]}] } {
            set nicspeed "Unknown"
        } else {
            set nicspeed "[format "%.0f" [expr {$nicspeed / 1000000000.0}]] Gbps"
        }
        lappend niclist "$nicdesc ($nicspeed)"
        $item destroy
    }
    $items destroy
    $wmi destroy
    dict set sysinfo nic [join $niclist "; "]
} err] } {
    dict set sysinfo nic "Unknown"
}
#Disk/Storage via WMI
if { [catch {
    set wmi [twapi::_wmi]
    set items [$wmi ExecQuery "SELECT Model,Size FROM Win32_DiskDrive"]
    set disklist [list]
    $items -iterate item {
        set diskmodel [$item -get Model]
        if { [catch {set disksize [$item -get Size]}] } {
            set disksize "Unknown"
        } else {
            set disksize "[format "%.0f" [expr {$disksize / 1073741824.0}]] GB"
        }
        lappend disklist "$diskmodel ($disksize)"
        $item destroy
    }
    $items destroy
    $wmi destroy
    dict set sysinfo storage [join $disklist "; "]
} err] } {
    dict set sysinfo storage "Unknown"
}
#Cloud Instance Detection
dict set sysinfo cloud_instance [DetectCloudInstance]
return $sysinfo
}

proc DetectCloudInstance {} {
#Detect cloud environment by checking metadata services
#AWS
if { [catch {
    package require http
    set tok [::http::geturl "http://169.254.169.254/latest/meta-data/instance-type" -timeout 1000]
    set itype [::http::data $tok]
    ::http::cleanup $tok
    if { $itype ne "" } { return "AWS $itype" }
} err] } { ; }
#Azure
if { [catch {
    package require http
    set tok [::http::geturl "http://169.254.169.254/metadata/instance/compute/vmSize?api-version=2021-02-01&format=text" -timeout 1000 -headers [list Metadata true]]
    set vmsize [::http::data $tok]
    ::http::cleanup $tok
    if { $vmsize ne "" } { return "Azure $vmsize" }
} err] } { ; }
#GCP
if { [catch {
    package require http
    set tok [::http::geturl "http://metadata.google.internal/computeMetadata/v1/instance/machine-type" -timeout 1000 -headers [list Metadata-Flavor Google]]
    set mtype [::http::data $tok]
    ::http::cleanup $tok
    if { $mtype ne "" } { return "GCP [file tail $mtype]" }
} err] } { ; }
return "Not Detected"
}

proc HowManyProcessorsLinux {} {
global cpu_model
    set fin [open /proc/cpuinfo r]
    set data [read $fin]; list
    close $fin
    set ::S(cpus) [llength [regexp -all -inline processor $data]]
    set ::S(cpus,list) {}
    for {set i 0} {$i < $::S(cpus)} {incr i} {
        lappend ::S(cpus,list) $i
    }
    foreach line [ split $data "\n" ] {
    if {[string match {model name*} $line]} {
    regexp {(.*):\ (.*)} $line all header cpu_model
    break
	}
    }
}

proc DiscoverSystemLinux {} {
global S cpu_model sysinfo
set sysinfo [dict create]
dict set sysinfo cpumodel $cpu_model
dict set sysinfo cpucount $S(cpus)
#OS Name and Version
if { [catch {
    if { [file exists /etc/os-release] } {
        set fin [open /etc/os-release r]
        set data [read $fin]
        close $fin
        foreach line [split $data "\n"] {
            if { [string match "PRETTY_NAME=*" $line] } {
                regexp {PRETTY_NAME="?([^"]*)"?} $line all os_name
                dict set sysinfo os_name $os_name
                break
            }
        }
    } else {
        set os_name [exec uname -s -r]
        dict set sysinfo os_name $os_name
    }
} err] } {
    dict set sysinfo os_name "Linux (version unavailable)"
}
#System Vendor and Type
if { [catch {
    if { [file exists /sys/class/dmi/id/sys_vendor] } {
        set fin [open /sys/class/dmi/id/sys_vendor r]
        set vendor [string trim [read $fin]]
        close $fin
        dict set sysinfo system_vendor $vendor
    } else {
        dict set sysinfo system_vendor "Unknown"
    }
} err] } {
    dict set sysinfo system_vendor "Unknown"
}
if { [catch {
    if { [file exists /sys/class/dmi/id/product_name] } {
        set fin [open /sys/class/dmi/id/product_name r]
        set product [string trim [read $fin]]
        close $fin
        dict set sysinfo system_type $product
    } else {
        dict set sysinfo system_type "Unknown"
    }
} err] } {
    dict set sysinfo system_type "Unknown"
}
#Total Memory from /proc/meminfo
if { [catch {
    set fin [open /proc/meminfo r]
    set data [read $fin]
    close $fin
    foreach line [split $data "\n"] {
        if { [string match "MemTotal:*" $line] } {
            regexp {MemTotal:\s+(\d+)\s+kB} $line all memkb
            set memgb [format "%.1f" [expr {$memkb / 1048576.0}]]
            dict set sysinfo memory "${memgb} GB"
            break
        }
    }
} err] } {
    dict set sysinfo memory "Unknown"
}
#NIC Information
if { [catch {
    set niclist [list]
    set netdir "/sys/class/net"
    if { [file exists $netdir] } {
        foreach iface [glob -nocomplain -directory $netdir *] {
            set ifname [file tail $iface]
            if { $ifname eq "lo" } continue
            set speed "Unknown"
            if { [file exists "$iface/speed"] } {
                catch {
                    set fin [open "$iface/speed" r]
                    set spd [string trim [read $fin]]
                    close $fin
                    if { [string is integer -strict $spd] && $spd > 0 } {
                        if { $spd >= 1000 } {
                            set speed "[expr {$spd / 1000}] Gbps"
                        } else {
                            set speed "${spd} Mbps"
                        }
                    }
                }
            }
            lappend niclist "$ifname ($speed)"
        }
    }
    if { [llength $niclist] > 0 } {
        dict set sysinfo nic [join $niclist "; "]
    } else {
        dict set sysinfo nic "Unknown"
    }
} err] } {
    dict set sysinfo nic "Unknown"
}
#Disk/Storage from lsblk
if { [catch {
    set disklist [list]
    set lsblkout [exec lsblk -dnbo NAME,SIZE,MODEL 2>/dev/null]
    foreach line [split $lsblkout "\n"] {
        set line [string trim $line]
        if { $line eq "" } continue
        set parts [regexp -all -inline {\S+} $line]
        set dname [lindex $parts 0]
        set dsize [lindex $parts 1]
        set dmodel [join [lrange $parts 2 end]]
        if { $dmodel eq "" } { set dmodel $dname }
        set dsizegb [format "%.0f" [expr {$dsize / 1073741824.0}]]
        lappend disklist "$dmodel (${dsizegb} GB)"
    }
    if { [llength $disklist] > 0 } {
        dict set sysinfo storage [join $disklist "; "]
    } else {
        dict set sysinfo storage "Unknown"
    }
} err] } {
    dict set sysinfo storage "Unknown"
}
#Cloud Instance Detection
dict set sysinfo cloud_instance [DetectCloudInstance]
return $sysinfo
}

proc ConfigureNetworkAgent { port restart } {
global agentlist S connectestablished
set chanlist [ lindex [ ::comm channels ] end ]
if { $chanlist eq "::Slave" } {
puts "Closing $chanlist connection"
if { [catch { $chanlist destroy } b] } {
puts "Error $b"
	}
}
if { [catch {::comm new Agent -listen 1 -local 0 -silent "TRUE" -port $port} b] } {
puts "Creation Failed : $b" } else {
puts "HammerDB Metric Agent active @ id [ Agent self ] hostname [ info hostname ] (Ctrl-C to Exit)"
Agent hook incoming {
global connectestablished
if { ![ info exists connectestablished ] } {
puts "Received a new display request from host $addr"
set connectestablished 1
	}
}
Agent hook lost {
global agentlist S connectestablished restart
set todel [ lsearch $agentlist $id ]
if { $todel != -1 } {
puts "Connection to display $id lost: $reason"
unset -nocomplain connectestablished
if {$restart} {
puts "Reinitializing HammerDB Metric Agent"
	} else {
puts "Closing HammerDB Metric Agent"
}
set agentlist [ lreplace $agentlist $todel $todel ]
set ::DONE 2
	}
}
Agent hook eval {
global agentlist S
if {[regexp {\"([0-9]+)\W([[:alnum:],[:punct:]]+)\"} $buffer all id host]} {
if { [ string match "*STOP*" $buffer ] } {
#Received Message to Stop Metrics before a Display connection
puts "Closing HammerDB Metric Agent"
::Agent destroy
exit
}	
lappend agentlist "$id $host"
puts "New display accepted @ $id $host"
#Start Gathering and Sending Metrics
StartMetrics
} else {
if {[regexp {\"Slave ([0-9]+)\W([[:alnum:],[:punct:]]+) disconnected\"} $buffer all id host]} {
set todel [ lsearch -exact $agentlist "$id $host" ]
if { $todel != -1 } {
set agentlist [ lreplace $agentlist $todel $todel ]
					}
				}
			}
		}
	}
}

proc isReadable {fin} {
global S iswin
    set status [catch { gets $fin line } result]
    if { $status != 0 } {
if { [catch { puts "error reading $fin: $result" } b] } { 
        #Error on the channel
	}
        set ::DONE 2
    } elseif { $result >= 0 } {
        #Successfully read the channel
if {![string match {[0-9]*} $line]} return
if  { $iswin eq "false" && $::S(gnice) eq "true" } {
	#rPrune gnice data
set line [ lreplace $line 10 10 ]
	}
if { [catch { SendOneLine $line } b] } { 
puts "Error Sending Data: $b"
	}
    } elseif { [eof $fin] } {
        set ::DONE 1
    } elseif { [fblocked $fin] } {
        # Read blocked.  Just return
    } else {
        # Something else
        puts "can't happen"
        set ::DONE 3
    }
}

proc StartMetrics {} {
global agentlist S cpu_model iswin sysinfo io_metrics_running
puts "Prepared CPU metrics for $cpu_model"
#Discover system information before sending metrics
if {$iswin} {
    if { [catch { set sysinfo [DiscoverSystemWindows] } err] } {
        puts "System discovery failed: $err"
        set sysinfo [dict create cpumodel $cpu_model cpucount $S(cpus)]
    }
} else {
    if { [catch { set sysinfo [DiscoverSystemLinux] } err] } {
        puts "System discovery failed: $err"
        set sysinfo [dict create cpumodel $cpu_model cpucount $S(cpus)]
    }
}
puts "System discovery complete: [dict size $sysinfo] fields gathered"
foreach f $agentlist {
puts -nonewline "Sending system discovery and CPU metrics to $f ..."
if { [catch {
Agent send $f DoDiscovery [list $sysinfo] agent
Agent send $f DoDisplay $S(cpus) [ list $cpu_model] agent
Agent send $f update
	} b] } {
puts "Failed $b"
} else {
puts "connection established"
                }
}
set io_metrics_running 1
after 2000 RunIOMetrics
if {$iswin} {
    if {[file exists "mpstat.bat"]} {
        set fin [open "| mpstat.bat" r]
    } elseif {[file exists "mpstat.exe"]} {
        set fin [open "| mpstat.exe" r]
    } else {
        puts "Neither mpstat.bat nor mpstat.exe were found."
    }
    } else {
    set fin [open "|mpstat -P ALL 2" r]
	}
    fconfigure $fin -blocking false
    fileevent $fin readable [list isReadable $fin] 
    vwait ::DONE
    set io_metrics_running 0
    close $fin
}

proc RunIOMetrics {} {
global iswin io_metrics_running
if {![info exists io_metrics_running] || !$io_metrics_running} {
    return
}
set iops 0.0
set mbps 0.0
if {$iswin} {
    if {[catch {lassign [CollectIOMetricsWindows] iops mbps}]} {
        set iops 0.0
        set mbps 0.0
    }
} else {
    if {[catch {set iom [CollectIOMetricsLinux]}]} {
        set iom {}
    }
    if {[llength $iom] eq 2} {
        lassign $iom iops mbps
    }
}
if {[string is double -strict $iops] && [string is double -strict $mbps]} {
    SendIOLine $iops $mbps
}
after 2000 RunIOMetrics
}

proc CollectIOMetricsLinux {} {
    global io_last_time io_last_reads io_last_writes io_last_sectors
    set now [clock milliseconds]
    if {[catch {set fin [open /proc/diskstats r]}]} {
        return {}
    }
    set reads 0
    set writes 0
    set sectors 0
    while {[gets $fin line] >= 0} {
        set fields [regexp -all -inline {\S+} $line]
        if {[llength $fields] < 14} { continue }
        set dev [lindex $fields 2]
        if {[regexp {^(loop|ram|fd|sr|dm-|md)} $dev]} { continue }
        set reads [expr {$reads + [lindex $fields 3]}]
        set writes [expr {$writes + [lindex $fields 7]}]
        set sectors [expr {$sectors + [lindex $fields 5] + [lindex $fields 9]}]
    }
    close $fin
    if {![info exists io_last_time]} {
        set io_last_time $now
        set io_last_reads $reads
        set io_last_writes $writes
        set io_last_sectors $sectors
        return {}
    }
    set dt [expr {($now - $io_last_time) / 1000.0}]
    if {$dt <= 0} { return {} }
    set diops [expr {(($reads - $io_last_reads) + ($writes - $io_last_writes)) / $dt}]
    set dmbps [expr {(($sectors - $io_last_sectors) * 512.0 / 1048576.0) / $dt}]
    set io_last_time $now
    set io_last_reads $reads
    set io_last_writes $writes
    set io_last_sectors $sectors
    if {$diops < 0} { set diops 0.0 }
    if {$dmbps < 0} { set dmbps 0.0 }
    return [list $diops $dmbps]
}

proc CollectIOMetricsWindows {} {
    global io_pdh_query
    if {![info exists io_pdh_query]} {
        if {[catch {set io_pdh_query [twapi::pdh_system_performance_query disk_transfer_per_sec disk_bytes_per_sec]}]} {
            return [list 0.0 0.0]
        }
        after 1000
    }
    catch {twapi::pdh_query_update $io_pdh_query}
    if {[catch {set perf_data [twapi::pdh_query_get $io_pdh_query]}]} {
        return [list 0.0 0.0]
    }
    set iops 0.0
    set mbps 0.0
    if {[dict exists $perf_data disk_transfer_per_sec]} {
        set iops [dict get $perf_data disk_transfer_per_sec]
    }
    if {[dict exists $perf_data disk_bytes_per_sec]} {
        set mbps [expr {[dict get $perf_data disk_bytes_per_sec] / 1048576.0}]
    }
    return [list $iops $mbps]
}

set agentlist ""

if $iswin { 
set maxcpus [ HowManyProcessorsWindows ]
	} else {	
if {! [file exists /proc/cpuinfo] || [auto_execok mpstat] eq ""} {
    puts "Linux mpstat error : check that mpstat command in sysstat package is installed"
    puts "HammerDB Metric Agent Terminated"
    return
	}
#sysstat from 10.1.2 includes additional column
set mpvgnice "10.1.2"
set mpversion  [ split [ exec mpstat -V ] ]
set mpv [ lindex $mpversion 2 ] 
set mpvcomp [ string compare $mpv $mpvgnice ]
if { $mpvcomp >= 0 } {
set ::S(gnice) true
	}
HowManyProcessorsLinux
  }

puts "Initializing HammerDB Metric Agent $version"
ConfigureNetworkAgent $port $restart
vwait ::DONE
while 1 {	
#Lost connection, reinitialize agent
::Agent destroy
unset -nocomplain ::DONE
if {$restart} {
ConfigureNetworkAgent $port $restart
vwait ::DONE
	} else {
exit
}
	}
